// Copyright 2021 IBM Corp
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package _import

import (
	"fmt"
	"os"
	"strings"
	"time"

	pmodels "github.com/IBM-Cloud/power-go-client/power/models"
	"github.com/IBM/platform-services-go-sdk/resourcecontrollerv2"
	"github.com/spf13/cobra"
	"k8s.io/klog/v2"
	"k8s.io/utils/ptr"

	"github.com/ppc64le-cloud/pvsadm/pkg"
	"github.com/ppc64le-cloud/pvsadm/pkg/client"
	"github.com/ppc64le-cloud/pvsadm/pkg/utils"
)

const (
	accessKeyId          = "access_key_id"
	cloudObjectStorage   = "cloud-object-storage"
	cosHmacKeys          = "cos_hmac_keys"
	crnServiceRoleWriter = "crn:v1:bluemix:public:iam::::serviceRole:Writer"
	imageStateActive     = "active"
	jobStateCompleted    = "completed"
	jobStateFailed       = "failed"
	secretAccessKey      = "secret_access_key"
	serviceCredPrefix    = "pvsadm-service-cred"
)

var Cmd = &cobra.Command{
	Use:   "import",
	Short: "Import the image into PowerVS workpace",
	Long: `Import the image into PowerVS workpace
pvsadm image import --help for information

# Set the API key or feed the --api-key commandline argument
export IBMCLOUD_API_KEY=<IBM_CLOUD_API_KEY>

# To Import the image across the two different IBM account use accesskey and secretkey options

# To Import the image from public bucket use public-bucket option

Examples:

# import image using default storage type (service credential will be autogenerated)
pvsadm image import -n upstream-core-lon04 -b <BUCKETNAME> --object rhel-83-10032020.ova.gz --pvs-image-name test-image -r <REGION>

# import image using default storage type with specifying the accesskey and secretkey explicitly
pvsadm image import -n upstream-core-lon04 -b <BUCKETNAME> --accesskey <ACCESSKEY> --secretkey <SECRETKEY> --object rhel-83-10032020.ova.gz --pvs-image-name test-image -r <REGION>

# with user provided storage type
pvsadm image import -n upstream-core-lon04 -b <BUCKETNAME> --pvs-storagetype <STORAGETYPE> --object rhel-83-10032020.ova.gz --pvs-image-name test-image -r <REGION>

# If user wants to specify the type of OS
pvsadm image import -n upstream-core-lon04 -b <BUCKETNAME> --object rhel-83-10032020.ova.gz --pvs-image-name test-image -r <REGION>

# import image from a public IBM Cloud Storage bucket
pvsadm image import -n upstream-core-lon04 -b <BUCKETNAME> --object rhel-83-10032020.ova.gz --pvs-image-name test-image -r <REGION> --public-bucket
`,
	PreRunE: func(cmd *cobra.Command, args []string) error {
		if pkg.ImageCMDOptions.WorkspaceID == "" && pkg.ImageCMDOptions.WorkspaceName == "" {
			return fmt.Errorf("--workspace-name or --workspace-id required")
		}

		// ensure that both, the AccessKey and SecretKey are either both set or unset
		if (len(pkg.ImageCMDOptions.AccessKey) > 0) != (len(pkg.ImageCMDOptions.SecretKey) > 0) {
			return fmt.Errorf("required both --accesskey and --secretkey values")
		}
		return nil
	},

	RunE: func(cmd *cobra.Command, args []string) error {
		opt := pkg.ImageCMDOptions
		apikey := pkg.Options.APIKey
		//validate inputs
		validStorageType := []string{"tier3", "tier1"}

		if !utils.Contains(validStorageType, strings.ToLower(opt.StorageType)) {
			klog.Errorf("provide valid StorageType. Allowable values are [tier1, tier3]")
			os.Exit(1)
		}

		pvsClient, err := client.NewClientWithEnv(apikey, pkg.Options.Environment, pkg.Options.Debug)
		if err != nil {
			return err
		}
		var accessKey, accessSecret string

		// Create AccessKey and SecretKey for the bucket provided if bucket access is private
		if (opt.AccessKey == "" || opt.SecretKey == "") && (!opt.Public) {
			// Find COS instance of the bucket
			listServiceInstanceOptions := &resourcecontrollerv2.ListResourceInstancesOptions{
				Type: ptr.To(cloudObjectStorage),
			}
			workspaces, _, err := pvsClient.ResouceControllerClient.ListResourceInstances(listServiceInstanceOptions)
			if err != nil {
				return fmt.Errorf("failed to list the resource instances: %v", err)
			}
			if len(workspaces.Resources) == 0 {
				return fmt.Errorf("there are no resouces under the resource instance shared")
			}
			getServiceInstanceOptions := &resourcecontrollerv2.GetResourceInstanceOptions{
				// TODO: possibility of workspaces to either be of type service_instance or composite_instance.
				ID: workspaces.Resources[0].ID,
			}

			cosInstance, _, err := pvsClient.ResouceControllerClient.GetResourceInstance(getServiceInstanceOptions)
			if err != nil {
				return fmt.Errorf("failed to list the resource instances: %v", err)
			}

			key, _, err := pvsClient.ResouceControllerClient.GetResourceKey(
				&resourcecontrollerv2.GetResourceKeyOptions{
					ID: cosInstance.ID,
				},
			)
			if err != nil {
				return fmt.Errorf("cannot find resource key: %v", err)
			}
			var ok bool

			// Create the service credential if does not exist
			if key.ID == nil {
				if opt.ServiceCredName == "" {
					opt.ServiceCredName = serviceCredPrefix + "-" + *cosInstance.Name
				}

				klog.V(2).Infof("Auto Generating the COS Service credential for importing the image with name: %s", opt.ServiceCredName)
				params := &resourcecontrollerv2.ResourceKeyPostParameters{}
				params.SetProperty("HMAC", true)

				key, _, err := pvsClient.ResouceControllerClient.CreateResourceKey(
					&resourcecontrollerv2.CreateResourceKeyOptions{
						Name:       ptr.To(opt.ServiceCredName),
						Source:     cosInstance.CRN,
						Role:       ptr.To(crnServiceRoleWriter),
						Parameters: params,
					},
				)
				if err != nil {
					return fmt.Errorf("unable to create resource key for service instance: %v", err.Error())
				}

				if key.Credentials == nil {
					return fmt.Errorf("no credentials associated with this instance")
				}
				if prop := key.Credentials.GetProperty(cosHmacKeys); prop != nil {
					if hmacKeys, ok := prop.(map[string]interface{}); !ok {
						return fmt.Errorf("type assertion for HMAC keys failed")
					} else {
						accessKey = hmacKeys[accessKeyId].(string)
						accessSecret = hmacKeys[secretAccessKey].(string)
					}
				} else {
					return fmt.Errorf("HMAC keys are not available with this instance")
				}

				if accessKey == "" || accessSecret == "" {
					return fmt.Errorf("unknown error occurred setting HMAC credentials")
				}
			} else {
				// Use the service credential already created
				klog.V(2).Info("Reading the existing service credential")

				if prop := key.Credentials.GetProperty(cosHmacKeys); prop != nil {
					cred, ok := prop.(map[string]interface{})
					if !ok {
						return fmt.Errorf("cannot find cos_hmac_keys")
					}
					accessKey = cred[accessKeyId].(string)
					accessSecret = cred[secretAccessKey].(string)
				}
			}
			if !ok {
				return fmt.Errorf("failed to get the accessKey and secretKey from service credential")
			}
			// Assign the Access Key and Secret Key for further operation
			opt.AccessKey = accessKey
			opt.SecretKey = accessSecret
		}

		pvmclient, err := client.NewPVMClientWithEnv(pvsClient, opt.WorkspaceID, opt.WorkspaceName, pkg.Options.Environment)
		if err != nil {
			return err
		}
		//By default Bucket Access is private
		bucketAccess := "private"

		if opt.Public {
			bucketAccess = "public"
		}
		klog.Infof("Importing image %s. Please wait...", opt.ImageName)
		jobRef, err := pvmclient.ImgClient.ImportImage(opt.ImageName, opt.ImageFilename, opt.Region,
			opt.AccessKey, opt.SecretKey, opt.BucketName, strings.ToLower(opt.StorageType), bucketAccess)
		if err != nil {
			return err
		}
		start := time.Now()
		err = utils.PollUntil(time.Tick(2*time.Minute), time.After(opt.WatchTimeout), func() (bool, error) {
			job, err := pvmclient.JobClient.Get(*jobRef.ID)
			if err != nil {
				return false, fmt.Errorf("image import job failed to complete, err: %v", err)
			}
			if *job.Status.State == jobStateCompleted {
				klog.Infof("Image imported successfully, took %s", time.Since(start))
				return true, nil
			}
			if *job.Status.State == jobStateFailed {
				return false, fmt.Errorf("image import job failed to complete, err: %v", job.Status.Message)
			}
			klog.Infof("Image import is in-progress, current state: %s", *job.Status.State)
			return false, nil
		})
		if err != nil {
			return err
		}

		var image *pmodels.ImageReference = &pmodels.ImageReference{}
		klog.V(1).Info("Retrieving image details")

		if image.ImageID == nil {
			image, err = pvmclient.ImgClient.GetImageByName(opt.ImageName)
			if err != nil {
				return err
			}
		}

		if !opt.Watch {
			klog.Infof("Image import for %s is currently in %s state, Please check the progress in the IBM cloud UI", *image.Name, *image.State)
			return nil
		}
		klog.Infof("Waiting for image %s to be active. Please wait...", opt.ImageName)
		start = time.Now()
		return utils.PollUntil(time.Tick(10*time.Second), time.After(opt.WatchTimeout), func() (bool, error) {
			img, err := pvmclient.ImgClient.Get(*image.ImageID)
			if err != nil {
				return false, fmt.Errorf("failed to import the image, err: %v\n\nRun the command \"pvsadm get events -i %s\" to get more information about the failure", err, pvmclient.InstanceID)
			}
			if img.State == imageStateActive {
				klog.Infof("Successfully imported the image: %s with ID: %s in %s", *image.Name, *image.ImageID, time.Since(start))
				return true, nil
			}
			klog.Infof("Waiting for image to be active. Current state: %s", img.State)
			return false, nil
		})
	},
}

func init() {
	// TODO pvs-instance-name and pvs-instance-id is deprecated and will be removed in a future release
	Cmd.Flags().StringVarP(&pkg.ImageCMDOptions.WorkspaceName, "pvs-instance-name", "n", "", "PowerVS Instance name.")
	Cmd.Flags().MarkDeprecated("pvs-instance-name", "pvs-instance-name is deprecated, workspace-name should be used")
	Cmd.Flags().StringVarP(&pkg.ImageCMDOptions.WorkspaceID, "pvs-instance-id", "i", "", "PowerVS Instance ID.")
	Cmd.Flags().MarkDeprecated("pvs-instance-id", "pvs-instance-id is deprecated, workspace-id should be used")
	Cmd.Flags().StringVarP(&pkg.ImageCMDOptions.WorkspaceName, "workspace-name", "", "", "PowerVS Workspace name.")
	Cmd.Flags().StringVarP(&pkg.ImageCMDOptions.WorkspaceID, "workspace-id", "", "", "PowerVS Workspace ID.")
	Cmd.Flags().StringVarP(&pkg.ImageCMDOptions.BucketName, "bucket", "b", "", "Cloud Object Storage bucket name.")
	Cmd.Flags().StringVarP(&pkg.ImageCMDOptions.COSInstanceName, "cos-instance-name", "s", "", "Cloud Object Storage instance name.")
	// TODO It's deprecated and will be removed in a future release
	Cmd.Flags().MarkDeprecated("cos-instance-name", "will be removed in a future version.")
	Cmd.Flags().StringVarP(&pkg.ImageCMDOptions.Region, "bucket-region", "r", "", "Cloud Object Storage bucket location.")
	Cmd.Flags().StringVarP(&pkg.ImageCMDOptions.ImageFilename, "object", "o", "", "Cloud Object Storage object name.")
	Cmd.Flags().StringVar(&pkg.ImageCMDOptions.AccessKey, "accesskey", "", "Cloud Object Storage HMAC access key.")
	Cmd.Flags().StringVar(&pkg.ImageCMDOptions.SecretKey, "secretkey", "", "Cloud Object Storage HMAC secret key.")
	Cmd.Flags().StringVar(&pkg.ImageCMDOptions.ImageName, "pvs-image-name", "", "Name to PowerVS imported image.")
	Cmd.Flags().BoolVarP(&pkg.ImageCMDOptions.Public, "public-bucket", "p", false, "Cloud Object Storage public bucket.")
	Cmd.Flags().BoolVarP(&pkg.ImageCMDOptions.Watch, "watch", "w", false, "After image import watch for image to be published and ready to use")
	Cmd.Flags().DurationVar(&pkg.ImageCMDOptions.WatchTimeout, "watch-timeout", 1*time.Hour, "watch timeout")
	Cmd.Flags().StringVar(&pkg.ImageCMDOptions.StorageType, "pvs-storagetype", "tier3", "PowerVS Storage type, accepted values are [tier1, tier3].")
	Cmd.Flags().StringVar(&pkg.ImageCMDOptions.ServiceCredName, "cos-service-cred", "", "IBM COS Service Credential name to be auto generated(default \""+serviceCredPrefix+"-<COS Name>\")")

	_ = Cmd.MarkFlagRequired("bucket")
	_ = Cmd.MarkFlagRequired("bucket-region")
	_ = Cmd.MarkFlagRequired("pvs-image-name")
	_ = Cmd.MarkFlagRequired("object")
	Cmd.Flags().SortFlags = false
}
